mqtt_server: 'localhost'
mqtt_port: '1883'
mqtt_user: 'user'
mqtt_password: "password"
mqtt_topic: "homeassistant/sensor/"
stib_api_key: 'secret_api_key_from_stibmivb.opendatasoft.com'
lang: 'fr' # fr or nl
message_lang: 'fr' # fr, nl or en
stop_names:
  - 'SAINT-DENIS'
  - 'MAX WALLER'
  - 'FOREST CENTRE'

