mqtt_server: 'localhost'
mqtt_port: '1883'
mqtt_user: 'username'
mqtt_password: 'password'
mqtt_topic: 'homeassistant/sensor'
stib_api_key: '022efe811eqkqeeoae35fbcca3abc88ah6854e6f418'
lang: 'fr'
message_lang: 'fr'
stop_names:
        - "MAX WALLER"
        - "SAINT-DENIS"
        - "FOREST CENTRE"
clean_on_start: 0
gtfs: false