mqtt_server: 'localhost'
mqtt_port: '1883'
mqtt_user: 'dan'
mqtt_password: 'mosJF26l9'
mqtt_topic: 'stib'
stib_api_key: '093d3250222cf7bb5b664e7b2f52a22efe811eabc882d16854e6f418'
lang: 'fr'
message_lang: 'fr'
stops:
  - stop_id: 5719
    line_numbers:
      - 12
      - 54
      - 74
      - 50
      - 'T82'
  - stop_id: 1015
    line_numbers: 
      - 50
      - 52 
  - stop_id: 1085
    line_numbers: 
      - 50
      - 82
  - stop_id: 3196 
    line_numbers:
      - 'T82'
      - 50
  - stop_id: 3194
    line_numbers:
      - 'T82'
      - 50
  - stop_id: 3247 
    line_numbers: 
      - 50
  - stop_id: 5152
    line_numbers:
      - 54
      - 50
      - 'T82'
  - stop_id: '5121F'
    line_numbers:
      - 82
  - stop_id: '5121'
    line_numbers:
      - 82
stop_names:
  - 'SAINT-DENIS'
  - 'MAX WALLER'
  - 'FOREST CENTRE'

test:
  - 5719:
    - 12
    - 54
    - 74
  - 1015:
    - 50
    - 82
